# Generated by Django 4.2.7 on 2023-11-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(default='perfil/iconuser.png', null=True, upload_to='perfil'),
        ),
    ]
